image: maven:3.8.6-eclipse-temurin-11

stages:
    - build
    - report

build:
    stage: build
    script:
        - mvn verify -P homework7-all-test
    artifacts:
        paths:
            - target/*.jar


allure_report:
    stage: report
    script:
        - mvn allure:report
    artifacts:
        paths:
            - target/site
